name: peerannot
channels:
  - conda-forge
dependencies:
  - python<3.14
  - jupyter
  - jupyter-cache
  - numpy
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - plotly
  - scikit-learn
  - tqdm
  - download
  - pooch
  - ipython
  - click
  - dash
  - dash-bootstrap-components
  - dash-daq
  - Pillow
  - pip:
    - peerannot>=0.0.1.post43
    - torch
    - torchvision
    - torchmetrics


